<?php

namespace Patryk\BookBundle\Repository;

/**
 * ReflectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReflectionRepository extends \Doctrine\ORM\EntityRepository
{
}
