patryk_book_homepage:
    path:     /
    defaults: { _controller: PatrykBookBundle:Default:index}

book:
    path:     /book/{chapter}
    defaults: { _controller: PatrykBookBundle:Default:book, chapter: null}

aboutme:
    path:     /aboutme
    defaults: { _controller: PatrykBookBundle:Default:aboutme}

reflection:
    path:     /reflection
    defaults: { _controller: PatrykBookBundle:Reflection:index }

new:
    path:     /reflection/new
    defaults: { _controller: PatrykBookBundle:Reflection:new }

create:
    path:     reflection/create
    defaults: { _controller: PatrykBookBundle:Reflection:create }
